"use client";

import { useEffect, useState } from "react";
import type { AgentId, Finding, FixResult, ScanInput } from "@/lib/types";

export function FixPanel({
  agentId,
  finding,
  scanInput,
  onClose,
}: {
  agentId: AgentId;
  finding: Finding;
  scanInput: ScanInput;
  onClose: () => void;
}) {
  const [state, setState] = useState<{ status: "loading" | "done" | "error"; result?: FixResult; error?: string }>({
    status: "loading",
  });

  useEffect(() => {
    let cancelled = false;

    async function run() {
      try {
        const res = await fetch("/api/fix", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ agentId, finding, scanInput }),
        });
        if (!res.ok) {
          const body = await res.json().catch(() => ({}));
          throw new Error(body.error ?? "Failed to generate a fix.");
        }
        const result = (await res.json()) as FixResult;
        if (!cancelled) setState({ status: "done", result });
      } catch (err) {
        if (!cancelled) setState({ status: "error", error: err instanceof Error ? err.message : "Something went wrong." });
      }
    }

    run();
    return () => {
      cancelled = true;
    };
  }, [agentId, finding, scanInput]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4" onClick={onClose}>
      <div className="max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
        <div className="mb-4 flex items-start justify-between">
          <h3 className="text-lg font-semibold text-slate-900">{finding.title}</h3>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600" aria-label="Close">
            ✕
          </button>
        </div>

        {state.status === "loading" && (
          <div className="flex items-center gap-3 py-8">
            <div className="h-6 w-6 animate-spin rounded-full border-2 border-indigo-200 border-t-indigo-600" />
            <p className="text-sm text-slate-500">AI is generating a fix…</p>
          </div>
        )}

        {state.status === "error" && <p className="py-4 text-sm text-red-600">{state.error}</p>}

        {state.status === "done" && state.result && (
          <div className="space-y-4">
            <div>
              <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">Before</p>
              <pre className="whitespace-pre-wrap rounded-lg bg-red-50 p-3 text-sm text-red-800 ring-1 ring-red-100">{state.result.before}</pre>
            </div>
            <div>
              <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">After</p>
              <pre className="whitespace-pre-wrap rounded-lg bg-green-50 p-3 text-sm text-green-800 ring-1 ring-green-100">{state.result.after}</pre>
            </div>
            <p className="text-sm text-slate-500">{state.result.explanation}</p>
            <p className="text-xs text-slate-400">
              {state.result.generatedBy === "ai" ? "Generated by Claude for this restaurant." : "Generated from a recommended-practice template."}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
